### check server status
GET http://localhost:8000/

# ====== Admin API =====#
### Post new admin user
POST http://localhost:8000/api/v1/admin-user
Content-Type: application/json

{
    "fName": "Subin",
    "lName": "Basnet",
    "email": "subin@basnet776889.com",
    "password": "subin",
    "phone": "98098098098",
    "address": "sydney",
    "dob": "2020-12-12"
}
### login admin user
POST http://localhost:8000/api/v1/admin-user/login
Content-Type: application/json

{

    "email": "messi@10.com",
    "password": "12"
    
}

### ======Category ===========###
### category new category
POST http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "status": "active",
    "name": "Furniture",
    "parentId": ""
}
### get categories
GET http://localhost:8000/api/v1/category/63699837a666496ad3688fbe
