### check server status
GET http://localhost:8000/

# ====== Admin API =====#
### Post new admin user
POST http://localhost:8000/api/v1/admin-user
Content-Type: application/json

{
    "fName": "Subin",
    "lName": "Basnet",
    "email": "subin@basnet776889.com",
    "password": "subin",
    "phone": "98098098098",
    "address": "sydney",
    "dob": "2020-12-12"
}


